
import java.sql.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class Citizen extends javax.swing.JFrame {

    /**
     * Creates new form Citizen
     */
    private int id;
    private Connection conn;
    /**
     * Creates new form Police
     */
    public Citizen() {
        initComponents();
        
    }
    Citizen(int id, Connection conn){
        this.id = id;
        System.out.println("Citizen : "+id);
        this.conn = conn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateleadbtn = new javax.swing.JButton();
        Viewleadsbtn = new javax.swing.JButton();
        giveleadbtn = new javax.swing.JButton();
        deleteleadbtn = new javax.swing.JButton();
        lwelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        updateleadbtn.setForeground(new java.awt.Color(0, 0, 204));
        updateleadbtn.setText("Update your Lead");
        updateleadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateleadbtnActionPerformed(evt);
            }
        });

        Viewleadsbtn.setText("View your Leads");
        Viewleadsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewleadsbtnActionPerformed(evt);
            }
        });

        giveleadbtn.setForeground(new java.awt.Color(0, 153, 51));
        giveleadbtn.setText("Give Lead");
        giveleadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveleadbtnActionPerformed(evt);
            }
        });

        deleteleadbtn.setForeground(new java.awt.Color(204, 0, 0));
        deleteleadbtn.setText("Delete your Lead");
        deleteleadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteleadbtnActionPerformed(evt);
            }
        });

        lwelcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lwelcome.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateleadbtn)
                .addGap(44, 44, 44)
                .addComponent(giveleadbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(deleteleadbtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Viewleadsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateleadbtn)
                    .addComponent(giveleadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteleadbtn))
                .addGap(66, 66, 66)
                .addComponent(Viewleadsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giveleadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveleadbtnActionPerformed
        GiveLead gl = new GiveLead(id,conn);
        gl.setVisible(true);
    }//GEN-LAST:event_giveleadbtnActionPerformed

    private void ViewleadsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewleadsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewleadsbtnActionPerformed

    private void updateleadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateleadbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateleadbtnActionPerformed

    private void deleteleadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteleadbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteleadbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Citizen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Viewleadsbtn;
    private javax.swing.JButton deleteleadbtn;
    private javax.swing.JButton giveleadbtn;
    private javax.swing.JLabel lwelcome;
    private javax.swing.JButton updateleadbtn;
    // End of variables declaration//GEN-END:variables
}
